Test 2 add randov products
andmysko/playwright_tests_with_po pull request #3
Opened 2024-12-02 17:20 UTC by andmysko

2024-12-02 20:49 UTC, ovartem requested changes
Really good PR. Even thought it's not working as expected the code looks really solid.

2024-12-02 20:49 UTC, ovartem commented on src/pages/Inventory.page.js
> +import _ from 'lodash';
looks like this one was added by mistake in this file.
let's remove it as you don't use it in this particular file

2024-12-02 20:49 UTC, ovartem commented on src/pages/ShoppingCart.page.js
> +    async getItemNameById(linkId) {
let's rename this method to be more self-explained.
Something like `getItemDataById`

2024-12-02 20:49 UTC, ovartem commented on src/tests/ShoppingCart.spec.js
> +        for (let i = 0; i < 3; i++) {
Let's move this logic to inventory page object

2024-12-02 20:49 UTC, ovartem commented on src/tests/ShoppingCart.spec.js
> +        for (let i = 0; i < 3; i++) {
Don't hardcode number 3

2024-12-02 20:49 UTC, ovartem commented on src/tests/ShoppingCart.spec.js
> +            const item = app.inventory.itemTitle.nth(randomNumber);
Let's simplifyu the logic and iterate over inventory_items (as parent) instead of operating individually item name, desc, price

2024-12-02 20:49 UTC, ovartem commented on src/tests/ShoppingCart.spec.js
> +        for (let i = 0; i < linkIds.length; i++) {
It's better to move this code to shoppingCart page object

2024-12-04 20:56 UTC, andmysko commented
@ovartem fixed. pls review

2024-12-04 21:09 UTC, EugenePetrik reviewed
Good job! Left a few comments

2024-12-04 21:09 UTC, EugenePetrik commented on src/pages/Inventory.page.js
> +    async AddRandomItemToTheCart(number, numbersOfItems) {
Method name should start from a letter in lower case `addRandomItemToTheCart()`

2024-12-04 21:09 UTC, EugenePetrik commented on src/pages/Inventory.page.js
> +        const SelectedItems = [];
The same for a variable `selectedItems`

2024-12-04 21:09 UTC, EugenePetrik commented on src/pages/ShoppingCart.page.js
> +    cartItemTitle = this.page.locator('[data-test="inventory-item-name"]');
We can use `getByTestId` method

```
cartItemTitle = this.page.getByTestId('inventory-item-name');
```

2024-12-04 21:09 UTC, EugenePetrik commented on src/tests/ShoppingCart.spec.js
> +        const quantityItemsToAdd = _.random(0, numbersOfItems - 1);
Based on the task, you should add 2 items to cart, in this case you add all items

2024-12-05 11:53 UTC, andmysko commented
@EugenePetrik  fixed. pls review

2024-12-05 20:38 UTC, ihorBohdvn commented on src/tests/ShoppingCart.spec.js
> +import { expect } from '@playwright/test';
Great job! Few little comments:
Rename the file to a more understandable name, for example, addProductsToCart.spec.js.

2024-12-05 20:40 UTC, kirstaVova commented on src/tests/ShoppingCart.spec.js
> +    test('Test 2   Add Random Products', async (
Change the name of Test 2 Add Random Products to something like Verify adding random products to cart.

2024-12-05 21:44 UTC, andmysko commented
@kirstaVova Thanks. Done. Pls review

2024-12-06 13:05 UTC, EugenePetrik approved these changes
Great job! Looks good 👍

2024-12-06 13:05 UTC, EugenePetrik commented on src/pages/Inventory.page.js
> +    parent = this.page.locator('.inventory_item');
We can use this

```
this.page.getByTestId('inventory-item');
```

2024-12-09 09:24 UTC, merged